services:
  orthanc:
    # image: cr.medoco.health/open-ortho/orthanc-mock:latest
    container_name: orthanc-mock
    image: jodogne/orthanc-plugins
    hostname: orthanc
    ports: ["127.0.0.1:8202:8042", "127.0.0.1:4242:4242"]
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json
    environment:
      VERBOSE_STARTUP: "true"
      VERBOSE_ENABLED: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__STONE_WEB_VIEWER__DATE_FORMAT: "YYYY-MM-DD"


  fhir2dicom4ortho:
    image: cr.medoco.health/open-ortho/fhir2dicom4ortho:latest
    container_name: fhir2dicom4ortho
    hostname: fhir2dicom4ortho
    ports: ["8203:8000"]
    environment:
      F2D4O_VERBOSITY: 2
      F2D4O_FHIR_LISTEN: ""
      F2D4O_FHIR_PORT: ""
      F2D4O_PACS_SEND_METHOD: "dimse"
      F2D4O_PACS_DIMSE_AET: "ORTHANC-MOCK"
      F2D4O_PACS_DIMSE_IP: "127.0.0.1"
 